#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine age_of_air_ad( im, km, jfirst, jlast, ng, time, pe, pe_ae, q_ae )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: p_source = 75000.
real(kind=r8), parameter :: tiny = 1.e-6

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
integer :: km
integer :: ng
real(kind=r8) :: pe(im,km+1,jfirst:jlast)
real(kind=r8) :: pe_ae(im,km+1,jfirst:jlast)
real(kind=r8) :: q_ae(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: time

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: k
#ifdef USE_OPENMP
real(kind=r8) :: pe_aeh(im,km+1,jfirst:jlast)
#endif /* ! USE_OPENMP */
real(kind=r8) :: pm
real(kind=r8) :: pm_ad

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
pm_ad = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
#ifdef USE_OPENMP
pe_aeh(:,:,:) = pe_ae(:,:,:)
!$omp parallel do shared(im,jfirst,jlast,km,pe,pe_aeh,q_ae,time) private(i,j,k,pe_ae,pm,pm_ad)
#endif /* ! USE_OPENMP */
do k = 1, km
#ifdef USE_OPENMP
  pe_ae(:,:,:) = 0.d0
#endif /* ! USE_OPENMP */
  pm_ad = 0.d0
  do j = jfirst, jlast
    pm_ad = 0.d0
    do i = 1, im
      pm_ad = 0.d0
      pm = 0.5*(pe(i,k,j)+pe(i,k+1,j))
      if (time .lt. tiny) then
        q_ae(i,j,k) = 0.d0
      else if (pm .ge. p_source) then
        q_ae(i,j,k) = 0.d0
      endif
      pe_ae(i,k+1,j) = pe_ae(i,k+1,j)+0.5*pm_ad
      pe_ae(i,k,j) = pe_ae(i,k,j)+0.5*pm_ad
      pm_ad = 0.d0
    end do
  end do
#ifdef USE_OPENMP
  !$omp critical  (adtaf)
  pe_aeh(:,:,:) = pe_aeh(:,:,:)+pe_ae(:,:,:)
  !$omp end critical (adtaf)
#endif /* ! USE_OPENMP */
end do
#ifdef USE_OPENMP
pe_ae(:,:,:) = pe_aeh(:,:,:)
#endif /* ! USE_OPENMP */

end subroutine age_of_air_ad


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine age_of_air_ad( im, km, jfirst, jlast, ng, time, pe, pe_ae, q_ae )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: p_source = 75000.
real(kind=r8), parameter :: tiny = 1.e-6

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
integer :: km
integer :: ng
real(kind=r8) :: pe(im,km+1,jfirst:jlast)
real(kind=r8) :: pe_ae(im,km+1,jfirst:jlast)
real(kind=r8) :: q_ae(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: time

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: k
#ifdef USE_OPENMP
real(kind=r8) :: pe_aeh(im,km+1,jfirst:jlast)
#endif /* ! USE_OPENMP */
real(kind=r8) :: pm
real(kind=r8) :: pm_ad

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
pm_ad = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
#ifdef USE_OPENMP
pe_aeh(:,:,:) = pe_ae(:,:,:)
!$omp parallel do shared(im,jfirst,jlast,km,pe,pe_aeh,q_ae,time) private(i,j,k,pe_ae,pm,pm_ad)
#endif /* ! USE_OPENMP */
do k = 1, km
#ifdef USE_OPENMP
  pe_ae(:,:,:) = 0.d0
#endif /* ! USE_OPENMP */
  pm_ad = 0.d0
  do j = jfirst, jlast
    pm_ad = 0.d0
    do i = 1, im
      pm_ad = 0.d0
      pm = 0.5*(pe(i,k,j)+pe(i,k+1,j))
      if (time .lt. tiny) then
        q_ae(i,j,k) = 0.d0
      else if (pm .ge. p_source) then
        q_ae(i,j,k) = 0.d0
      endif
      pe_ae(i,k+1,j) = pe_ae(i,k+1,j)+0.5*pm_ad
      pe_ae(i,k,j) = pe_ae(i,k,j)+0.5*pm_ad
      pm_ad = 0.d0
    end do
  end do
#ifdef USE_OPENMP
  !$omp critical  (adtaf)
  pe_aeh(:,:,:) = pe_aeh(:,:,:)+pe_ae(:,:,:)
  !$omp end critical (adtaf)
#endif /* ! USE_OPENMP */
end do
#ifdef USE_OPENMP
pe_ae(:,:,:) = pe_aeh(:,:,:)
#endif /* ! USE_OPENMP */

end subroutine age_of_air_ad


#endif /* SPMD */
