#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine avgc_ad( aa_ad, ac_ad, im, jm, jfirst, jlast, wk_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
real(kind=r8) :: aa_ad(im,jfirst-1:jlast+1)
real(kind=r8), intent(inout) :: ac_ad(im,jfirst:jlast+1)
integer :: jm
real(kind=r8) :: wk_ad(im,jfirst-1:jlast+1)

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: jn1g1
integer :: js1g1
integer :: js2g0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
js1g1 = max(jfirst-1,1)
js2g0 = max(jfirst,2)
jn1g1 = min(jlast+1,jm)
do j = js2g0, jn1g1
  do i = 1, im
    wk_ad(i,j-1) = wk_ad(i,j-1)+ac_ad(i,j)
    wk_ad(i,j) = wk_ad(i,j)+ac_ad(i,j)
    ac_ad(i,j) = 0.
  end do
end do
do j = js1g1, jn1g1
  do i = 2, im
    aa_ad(i-1,j) = aa_ad(i-1,j)+wk_ad(i,j)
    aa_ad(i,j) = aa_ad(i,j)+wk_ad(i,j)
    wk_ad(i,j) = 0.d0
  end do
  aa_ad(im,j) = aa_ad(im,j)+wk_ad(1,j)
  aa_ad(1,j) = aa_ad(1,j)+wk_ad(1,j)
  wk_ad(1,j) = 0.d0
end do

end subroutine avgc_ad


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine avgc_ad( aa_ad, ac_ad, im, jm, jfirst, jlast, wk_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
real(kind=r8) :: aa_ad(im,jfirst-1:jlast+1)
real(kind=r8), intent(inout) :: ac_ad(im,jfirst:jlast+1)
integer :: jm
real(kind=r8) :: wk_ad(im,jfirst-1:jlast+1)

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: jn1g1
integer :: js1g1
integer :: js2g0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
js1g1 = max(jfirst-1,1)
js2g0 = max(jfirst,2)
jn1g1 = min(jlast+1,jm)
do j = js2g0, jn1g1
  do i = 1, im
    wk_ad(i,j-1) = wk_ad(i,j-1)+ac_ad(i,j)
    wk_ad(i,j) = wk_ad(i,j)+ac_ad(i,j)
    ac_ad(i,j) = 0.
  end do
end do
do j = js1g1, jn1g1
  do i = 2, im
    aa_ad(i-1,j) = aa_ad(i-1,j)+wk_ad(i,j)
    aa_ad(i,j) = aa_ad(i,j)+wk_ad(i,j)
    wk_ad(i,j) = 0.d0
  end do
  aa_ad(im,j) = aa_ad(im,j)+wk_ad(1,j)
  aa_ad(1,j) = aa_ad(1,j)+wk_ad(1,j)
  wk_ad(1,j) = 0.d0
end do

end subroutine avgc_ad


#endif /* SPMD */
