#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     prognostics_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision
use prognostics

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare local variables
!==============================================
real(kind=r8), save, allocatable :: pe_ad(:,:,:)
real(kind=r8), save, allocatable :: pk_ad(:,:,:)
real(kind=r8), save, allocatable :: pkz_ad(:,:,:)
real(kind=r8), save, allocatable :: ps_ad(:,:)

contains
subroutine prognostics_final_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!----------------------------------------------
! DEALLOCATE MODULE VARIABLES
!----------------------------------------------
deallocate( pe_ad )
deallocate( pk_ad )
deallocate( pkz_ad )
deallocate( ps_ad )

end subroutine prognostics_final_ad


subroutine prognostics_initial_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!----------------------------------------------
! ALLOCATE AND RESET MODULE VARIABLES
!----------------------------------------------
allocate( pe_ad(lbound(pe,1):ubound(pe,1),lbound(pe,2):ubound(pe,2),lbound(pe,3):ubound(pe,3)) )
pe_ad(:,:,:) = 0.
allocate( pk_ad(lbound(pk,1):ubound(pk,1),lbound(pk,2):ubound(pk,2),lbound(pk,3):ubound(pk,3)) )
pk_ad(:,:,:) = 0.
allocate( pkz_ad(lbound(pkz,1):ubound(pkz,1),lbound(pkz,2):ubound(pkz,2),lbound(pkz,3):ubound(pkz,3)) )
pkz_ad(:,:,:) = 0.
allocate( ps_ad(lbound(ps,1):ubound(ps,1),lbound(ps,2):ubound(ps,2)) )
ps_ad(:,:) = 0.

end subroutine prognostics_initial_ad


end module     prognostics_ad


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     prognostics_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision
use prognostics

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare local variables
!==============================================
real(kind=r8), allocatable :: delp_ad(:,:,:)
real(kind=r8), allocatable :: pe_ad(:,:,:)
real(kind=r8), allocatable :: pk_ad(:,:,:)
real(kind=r8), allocatable :: pkz_ad(:,:,:)
real(kind=r8), allocatable :: ps_ad(:,:)
real(kind=r8), allocatable :: pt_ad(:,:,:)
real(kind=r8), allocatable :: q_ad(:,:,:,:)
real(kind=r8), allocatable :: u_ad(:,:,:)
real(kind=r8), allocatable :: v_ad(:,:,:)

contains
subroutine prognostics_final_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!----------------------------------------------
! DEALLOCATE MODULE VARIABLES
!----------------------------------------------
deallocate( delp_ad )
deallocate( pe_ad )
deallocate( pk_ad )
deallocate( pkz_ad )
deallocate( ps_ad )
deallocate( pt_ad )
deallocate( q_ad )
deallocate( u_ad )
deallocate( v_ad )

end subroutine prognostics_final_ad


subroutine prognostics_initial_ad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!----------------------------------------------
! ALLOCATE AND RESET MODULE VARIABLES
!----------------------------------------------
allocate( delp_ad(lbound(delp,1):ubound(delp,1),lbound(delp,2):ubound(delp,2),lbound(delp,3):ubound(delp,3)) )
delp_ad(:,:,:) = 0.
allocate( pe_ad(lbound(pe,1):ubound(pe,1),lbound(pe,2):ubound(pe,2),lbound(pe,3):ubound(pe,3)) )
pe_ad(:,:,:) = 0.
allocate( pk_ad(lbound(pk,1):ubound(pk,1),lbound(pk,2):ubound(pk,2),lbound(pk,3):ubound(pk,3)) )
pk_ad(:,:,:) = 0.
allocate( pkz_ad(lbound(pkz,1):ubound(pkz,1),lbound(pkz,2):ubound(pkz,2),lbound(pkz,3):ubound(pkz,3)) )
pkz_ad(:,:,:) = 0.
allocate( ps_ad(lbound(ps,1):ubound(ps,1),lbound(ps,2):ubound(ps,2)) )
ps_ad(:,:) = 0.
allocate( pt_ad(lbound(pt,1):ubound(pt,1),lbound(pt,2):ubound(pt,2),lbound(pt,3):ubound(pt,3)) )
pt_ad(:,:,:) = 0.
allocate( q_ad(lbound(q,1):ubound(q,1),lbound(q,2):ubound(q,2),lbound(q,3):ubound(q,3),lbound(q,4):ubound(q,4)) )
q_ad(:,:,:,:) = 0.
allocate( u_ad(lbound(u,1):ubound(u,1),lbound(u,2):ubound(u,2),lbound(u,3):ubound(u,3)) )
u_ad(:,:,:) = 0.
allocate( v_ad(lbound(v,1):ubound(v,1),lbound(v,2):ubound(v,2),lbound(v,3):ubound(v,3)) )
v_ad(:,:,:) = 0.

end subroutine prognostics_initial_ad


end module     prognostics_ad


#endif /* SPMD */
