#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     fill_module_tad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fill_module

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

contains
subroutine filew_tad( q, q_tae, im, jm, jfirst, jlast, acap, tiny, cosp2 )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
real(kind=r8) :: cosp2
integer :: im
integer :: jfirst
integer :: jlast
integer :: jm
real(kind=r8) :: q(im,jfirst:jlast)
real(kind=r8) :: q_tae(im,jfirst:jlast)
real(kind=r8) :: tiny

!==============================================
! declare local variables
!==============================================
real(kind=r8) :: d0
real(kind=r8) :: d0_tad
real(kind=r8) :: d1
real(kind=r8) :: d1_tad
real(kind=r8) :: d2
real(kind=r8) :: d2_tad
integer :: i
integer :: ib1
integer :: ib2
integer :: ip2
integer :: ipx
integer :: j
integer :: j1
integer :: j2
integer :: jb2
integer :: jb3
integer :: jb5
integer :: jb6
integer :: jb7
integer :: jb8
integer :: jm1
real(kind=r8) :: qh(im,jfirst:jlast)
real(kind=r8) :: qtmp(jfirst:jlast,im)
real(kind=r8) :: qtmp_tad(jfirst:jlast,im)

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
qh(:,:) = q(:,:)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
d0_tad = 0.d0
d1_tad = 0.d0
d2_tad = 0.d0
qtmp_tad(:,:) = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
j1 = max(jfirst,2)
j2 = min(jlast,jm-1)
jm1 = jm-1
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im, 2, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      q(i,j) = qtmp(j,i)
    end do
  end do
endif
if (jfirst .eq. 1) then
  if (q(1,1) .lt. 0.) then
    call pfix( q(1,2),q(1,1),im,ipx,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,2) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix( q(1,2),q(1,1),im,ipx,acap,cosp2 )
    endif
  endif
endif
if (jlast .eq. jm) then
  if (q(1,jm) .lt. 0.) then
    call pfix_tad( q_tae(1,jm1),q_tae(1,jm),im,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,jm1) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix_tad( q_tae(1,jm1),q_tae(1,jm),im,acap,cosp2 )
    endif
  endif
endif
q(:,:) = qh(:,:)
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im, 2, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      q(i,j) = qtmp(j,i)
    end do
  end do
endif
if (jfirst .eq. 1) then
  if (q(1,1) .lt. 0.) then
    call pfix_tad( q_tae(1,2),q_tae(1,1),im,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,2) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix_tad( q_tae(1,2),q_tae(1,1),im,acap,cosp2 )
    endif
  endif
endif
q(:,:) = qh(:,:)
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      qtmp_tad(j,i) = qtmp_tad(j,i)+q_tae(i,j)
      q_tae(i,j) = 0.d0
    end do
  end do
  do i = im, 3, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = 2, im
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp_tad(j,i) = 0.d0
        qtmp_tad(j,i) = qtmp_tad(j,i)+qtmp_tad(j,i-1)
      endif
    end do
  end do
  q(:,:) = qh(:,:)
  do i = 1, im
    do j = j1, j2
      qtmp(j,i) = q(i,j)
    end do
  end do
  do i = 2, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        d0 = max(0._8,qtmp(j,i-1))
        d1 = min(-qtmp(j,i),d0)
        qtmp(j,i-1) = qtmp(j,i-1)-d1
        qtmp(j,i) = qtmp(j,i)+d1
        d0 = max(0._8,qtmp(j,i+1))
        d2 = min(-qtmp(j,i),d0)
        qtmp(j,i+1) = qtmp(j,i+1)-d2
        qtmp(j,i) = qtmp(j,i)+d2+tiny
      endif
    end do
  end do
  i = 1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,im))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,im) = qtmp(j,im)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
  i = im
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,1) = qtmp(j,1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
  do i = 1, (-2)+im
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im-1, 1, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp_tad(j,i) = 0.d0
        qtmp_tad(j,i) = qtmp_tad(j,i)+qtmp_tad(j,i+1)
      endif
    end do
  end do
endif
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2_tad = d2_tad+qtmp_tad(j,i)
    d2_tad = d2_tad-qtmp_tad(j,1)
    d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d2_tad = 0.d0
    qtmp_tad(j,1) = qtmp_tad(j,1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,1)))
    d0_tad = 0.d0
    d1_tad = d1_tad+qtmp_tad(j,i)
    d1_tad = d1_tad-qtmp_tad(j,i-1)
    do i = 1, im
      do jb2 = j1, j2
        qtmp(jb2,i) = q(i,jb2)
      end do
    end do
    do i = 2, im-1
      do jb2 = j1, j2
        if (qtmp(jb2,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb2,i-1))
          d1 = min(-qtmp(jb2,i),d0)
          qtmp(jb2,i-1) = qtmp(jb2,i-1)-d1
          qtmp(jb2,i) = qtmp(jb2,i)+d1
          d0 = max(0._8,qtmp(jb2,i+1))
          d2 = min(-qtmp(jb2,i),d0)
          qtmp(jb2,i+1) = qtmp(jb2,i+1)-d2
          qtmp(jb2,i) = qtmp(jb2,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    do jb2 = j1, j2
      if (qtmp(jb2,i) .lt. 0.) then
        d0 = max(0._8,qtmp(jb2,im))
        d1 = min(-qtmp(jb2,i),d0)
        qtmp(jb2,im) = qtmp(jb2,im)-d1
        qtmp(jb2,i) = qtmp(jb2,i)+d1
        d0 = max(0._8,qtmp(jb2,i+1))
        d2 = min(-qtmp(jb2,i),d0)
        qtmp(jb2,i+1) = qtmp(jb2,i+1)-d2
        qtmp(jb2,i) = qtmp(jb2,i)+d2+tiny
      endif
    end do
    i = im
    d0 = max(0._8,qtmp(j,i-1))
    d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d1_tad = 0.d0
    do i = 1, im
      do jb3 = j1, j2
        qtmp(jb3,i) = q(i,jb3)
      end do
    end do
    do i = 2, im-1
      do jb3 = j1, j2
        if (qtmp(jb3,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb3,i-1))
          d1 = min(-qtmp(jb3,i),d0)
          qtmp(jb3,i-1) = qtmp(jb3,i-1)-d1
          qtmp(jb3,i) = qtmp(jb3,i)+d1
          d0 = max(0._8,qtmp(jb3,i+1))
          d2 = min(-qtmp(jb3,i),d0)
          qtmp(jb3,i+1) = qtmp(jb3,i+1)-d2
          qtmp(jb3,i) = qtmp(jb3,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    do jb3 = j1, j2
      if (qtmp(jb3,i) .lt. 0.) then
        d0 = max(0._8,qtmp(jb3,im))
        d1 = min(-qtmp(jb3,i),d0)
        qtmp(jb3,im) = qtmp(jb3,im)-d1
        qtmp(jb3,i) = qtmp(jb3,i)+d1
        d0 = max(0._8,qtmp(jb3,i+1))
        d2 = min(-qtmp(jb3,i),d0)
        qtmp(jb3,i+1) = qtmp(jb3,i+1)-d2
        qtmp(jb3,i) = qtmp(jb3,i)+d2+tiny
      endif
    end do
    i = im
    qtmp_tad(j,i-1) = qtmp_tad(j,i-1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i-1)))
    d0_tad = 0.d0
  endif
end do
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2_tad = d2_tad+qtmp_tad(j,i)
    d2_tad = d2_tad-qtmp_tad(j,i+1)
    d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d2_tad = 0.d0
    qtmp_tad(j,i+1) = qtmp_tad(j,i+1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i+1)))
    d0_tad = 0.d0
    d1_tad = d1_tad+qtmp_tad(j,i)
    d1_tad = d1_tad-qtmp_tad(j,im)
    do i = 1, im
      do jb5 = j1, j2
        qtmp(jb5,i) = q(i,jb5)
      end do
    end do
    do i = 2, im-1
      do jb5 = j1, j2
        if (qtmp(jb5,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb5,i-1))
          d1 = min(-qtmp(jb5,i),d0)
          qtmp(jb5,i-1) = qtmp(jb5,i-1)-d1
          qtmp(jb5,i) = qtmp(jb5,i)+d1
          d0 = max(0._8,qtmp(jb5,i+1))
          d2 = min(-qtmp(jb5,i),d0)
          qtmp(jb5,i+1) = qtmp(jb5,i+1)-d2
          qtmp(jb5,i) = qtmp(jb5,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    d0 = max(0._8,qtmp(j,im))
    d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d1_tad = 0.d0
    do i = 1, im
      do jb6 = j1, j2
        qtmp(jb6,i) = q(i,jb6)
      end do
    end do
    do i = 2, im-1
      do jb6 = j1, j2
        if (qtmp(jb6,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb6,i-1))
          d1 = min(-qtmp(jb6,i),d0)
          qtmp(jb6,i-1) = qtmp(jb6,i-1)-d1
          qtmp(jb6,i) = qtmp(jb6,i)+d1
          d0 = max(0._8,qtmp(jb6,i+1))
          d2 = min(-qtmp(jb6,i),d0)
          qtmp(jb6,i+1) = qtmp(jb6,i+1)-d2
          qtmp(jb6,i) = qtmp(jb6,i)+d2+tiny
        endif
      end do
    end do
    qtmp_tad(j,im) = qtmp_tad(j,im)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,im)))
    d0_tad = 0.d0
  endif
end do
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  do j = j1, j2
    d0_tad = 0.d0
    d1_tad = 0.d0
    d2_tad = 0.d0
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2_tad = d2_tad+qtmp_tad(j,i)
      d2_tad = d2_tad-qtmp_tad(j,i+1)
      d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
      qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
      d2_tad = 0.d0
      qtmp_tad(j,i+1) = qtmp_tad(j,i+1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i+1)))
      d0_tad = 0.d0
      d1_tad = d1_tad+qtmp_tad(j,i)
      d1_tad = d1_tad-qtmp_tad(j,i-1)
      do ib1 = 1, im
        do jb7 = j1, j2
          qtmp(jb7,ib1) = q(ib1,jb7)
        end do
      end do
      d0 = max(0._8,qtmp(j,i-1))
      d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
      qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
      d1_tad = 0.d0
      do ib2 = 1, im
        do jb8 = j1, j2
          qtmp(jb8,ib2) = q(ib2,jb8)
        end do
      end do
      qtmp_tad(j,i-1) = qtmp_tad(j,i-1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i-1)))
      d0_tad = 0.d0
    endif
  end do
end do
do i = 1, im
  do j = j1, j2
    q_tae(i,j) = q_tae(i,j)+qtmp_tad(j,i)
    qtmp_tad(j,i) = 0.d0
  end do
end do

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine filew_tad


subroutine fillxy_tad( q, q_tae, im, jm, jfirst, jlast, acap, cosp )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: tiny = 1.e-20

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
integer :: jm
real(kind=r8) :: cosp(jm)
integer :: im
integer :: jfirst
integer :: jlast
real(kind=r8) :: q(im,jfirst:jlast)
real(kind=r8) :: q_tae(im,jfirst:jlast)

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
call filew_tad( q,q_tae,im,jm,jfirst,jlast,acap,tiny,cosp(2) )

end subroutine fillxy_tad


subroutine pfix_tad( q_tae, qp_tad, im, acap, cosp2 )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
real(kind=r8) :: cosp2
integer :: im
real(kind=r8) :: q_tae(im)
real(kind=r8) :: qp_tad(im)

!==============================================
! declare local variables
!==============================================
integer :: i
real(kind=r8) :: pmean_tad
real(kind=r8) :: summ_tad
real(kind=r8) :: sump_tad

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
pmean_tad = 0.d0
summ_tad = 0.d0
sump_tad = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
do i = 1, im
  pmean_tad = pmean_tad+qp_tad(i)
  qp_tad(i) = 0.d0
  pmean_tad = pmean_tad+q_tae(i)
  q_tae(i) = 0.d0
end do
summ_tad = summ_tad+pmean_tad*(cosp2/(acap+cosp2*im))
sump_tad = sump_tad+pmean_tad*(acap/(acap+cosp2*im))
pmean_tad = 0.d0
sump_tad = sump_tad/dble(im)
do i = 1, im
  qp_tad(i) = qp_tad(i)+sump_tad
  q_tae(i) = q_tae(i)+summ_tad
end do

end subroutine pfix_tad


end module     fill_module_tad


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     fill_module_tad
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fill_module

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

contains
subroutine filew_tad( q, q_tae, im, jm, jfirst, jlast, acap, tiny, cosp2 )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
real(kind=r8) :: cosp2
integer :: im
integer :: jfirst
integer :: jlast
integer :: jm
real(kind=r8) :: q(im,jfirst:jlast)
real(kind=r8) :: q_tae(im,jfirst:jlast)
real(kind=r8) :: tiny

!==============================================
! declare local variables
!==============================================
real(kind=r8) :: d0
real(kind=r8) :: d0_tad
real(kind=r8) :: d1
real(kind=r8) :: d1_tad
real(kind=r8) :: d2
real(kind=r8) :: d2_tad
integer :: i
integer :: ib1
integer :: ib2
integer :: ip2
integer :: ipx
integer :: j
integer :: j1
integer :: j2
integer :: jb2
integer :: jb3
integer :: jb5
integer :: jb6
integer :: jb7
integer :: jb8
integer :: jm1
real(kind=r8) :: qh(im,jfirst:jlast)
real(kind=r8) :: qtmp(jfirst:jlast,im)
real(kind=r8) :: qtmp_tad(jfirst:jlast,im)

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
qh(:,:) = q(:,:)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
d0_tad = 0.d0
d1_tad = 0.d0
d2_tad = 0.d0
qtmp_tad(:,:) = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
j1 = max(jfirst,2)
j2 = min(jlast,jm-1)
jm1 = jm-1
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im, 2, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      q(i,j) = qtmp(j,i)
    end do
  end do
endif
if (jfirst .eq. 1) then
  if (q(1,1) .lt. 0.) then
    call pfix( q(1,2),q(1,1),im,ipx,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,2) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix( q(1,2),q(1,1),im,ipx,acap,cosp2 )
    endif
  endif
endif
if (jlast .eq. jm) then
  if (q(1,jm) .lt. 0.) then
    call pfix_tad( q_tae(1,jm1),q_tae(1,jm),im,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,jm1) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix_tad( q_tae(1,jm1),q_tae(1,jm),im,acap,cosp2 )
    endif
  endif
endif
q(:,:) = qh(:,:)
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im, 2, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      q(i,j) = qtmp(j,i)
    end do
  end do
endif
if (jfirst .eq. 1) then
  if (q(1,1) .lt. 0.) then
    call pfix_tad( q_tae(1,2),q_tae(1,1),im,acap,cosp2 )
  else
    ip2 = 0
    do i = 1, im
      if (q(i,2) .lt. 0.) then
        ip2 = 1
        exit
      endif
    end do
    if (ip2 .ne. 0) then
      call pfix_tad( q_tae(1,2),q_tae(1,1),im,acap,cosp2 )
    endif
  endif
endif
q(:,:) = qh(:,:)
ipx = 0
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      ipx = 1
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    ipx = 1
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,1) = qtmp(j,1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
if (ipx .ne. 0) then
  do i = 1, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do j = j1, j2
    do i = 1, im
      qtmp_tad(j,i) = qtmp_tad(j,i)+q_tae(i,j)
      q_tae(i,j) = 0.d0
    end do
  end do
  do i = im, 3, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i-1) = qtmp(j,i-1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = 2, im
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp_tad(j,i) = 0.d0
        qtmp_tad(j,i) = qtmp_tad(j,i)+qtmp_tad(j,i-1)
      endif
    end do
  end do
  q(:,:) = qh(:,:)
  do i = 1, im
    do j = j1, j2
      qtmp(j,i) = q(i,j)
    end do
  end do
  do i = 2, im-1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        d0 = max(0._8,qtmp(j,i-1))
        d1 = min(-qtmp(j,i),d0)
        qtmp(j,i-1) = qtmp(j,i-1)-d1
        qtmp(j,i) = qtmp(j,i)+d1
        d0 = max(0._8,qtmp(j,i+1))
        d2 = min(-qtmp(j,i),d0)
        qtmp(j,i+1) = qtmp(j,i+1)-d2
        qtmp(j,i) = qtmp(j,i)+d2+tiny
      endif
    end do
  end do
  i = 1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,im))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,im) = qtmp(j,im)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
  i = im
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,1) = qtmp(j,1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
  do i = 1, (-2)+im
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp(j,i+1) = qtmp(j,i+1)+qtmp(j,i)
        qtmp(j,i) = 0.
      endif
    end do
  end do
  do i = im-1, 1, -1
    do j = j1, j2
      if (qtmp(j,i) .lt. 0.) then
        qtmp_tad(j,i) = 0.d0
        qtmp_tad(j,i) = qtmp_tad(j,i)+qtmp_tad(j,i+1)
      endif
    end do
  end do
endif
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2 = min(-qtmp(j,i),d0)
    qtmp(j,i+1) = qtmp(j,i+1)-d2
    qtmp(j,i) = qtmp(j,i)+d2+tiny
  endif
end do
i = im
do j = j1, j2
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,i-1))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,i-1) = qtmp(j,i-1)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,1))
    d2_tad = d2_tad+qtmp_tad(j,i)
    d2_tad = d2_tad-qtmp_tad(j,1)
    d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d2_tad = 0.d0
    qtmp_tad(j,1) = qtmp_tad(j,1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,1)))
    d0_tad = 0.d0
    d1_tad = d1_tad+qtmp_tad(j,i)
    d1_tad = d1_tad-qtmp_tad(j,i-1)
    do i = 1, im
      do jb2 = j1, j2
        qtmp(jb2,i) = q(i,jb2)
      end do
    end do
    do i = 2, im-1
      do jb2 = j1, j2
        if (qtmp(jb2,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb2,i-1))
          d1 = min(-qtmp(jb2,i),d0)
          qtmp(jb2,i-1) = qtmp(jb2,i-1)-d1
          qtmp(jb2,i) = qtmp(jb2,i)+d1
          d0 = max(0._8,qtmp(jb2,i+1))
          d2 = min(-qtmp(jb2,i),d0)
          qtmp(jb2,i+1) = qtmp(jb2,i+1)-d2
          qtmp(jb2,i) = qtmp(jb2,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    do jb2 = j1, j2
      if (qtmp(jb2,i) .lt. 0.) then
        d0 = max(0._8,qtmp(jb2,im))
        d1 = min(-qtmp(jb2,i),d0)
        qtmp(jb2,im) = qtmp(jb2,im)-d1
        qtmp(jb2,i) = qtmp(jb2,i)+d1
        d0 = max(0._8,qtmp(jb2,i+1))
        d2 = min(-qtmp(jb2,i),d0)
        qtmp(jb2,i+1) = qtmp(jb2,i+1)-d2
        qtmp(jb2,i) = qtmp(jb2,i)+d2+tiny
      endif
    end do
    i = im
    d0 = max(0._8,qtmp(j,i-1))
    d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d1_tad = 0.d0
    do i = 1, im
      do jb3 = j1, j2
        qtmp(jb3,i) = q(i,jb3)
      end do
    end do
    do i = 2, im-1
      do jb3 = j1, j2
        if (qtmp(jb3,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb3,i-1))
          d1 = min(-qtmp(jb3,i),d0)
          qtmp(jb3,i-1) = qtmp(jb3,i-1)-d1
          qtmp(jb3,i) = qtmp(jb3,i)+d1
          d0 = max(0._8,qtmp(jb3,i+1))
          d2 = min(-qtmp(jb3,i),d0)
          qtmp(jb3,i+1) = qtmp(jb3,i+1)-d2
          qtmp(jb3,i) = qtmp(jb3,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    do jb3 = j1, j2
      if (qtmp(jb3,i) .lt. 0.) then
        d0 = max(0._8,qtmp(jb3,im))
        d1 = min(-qtmp(jb3,i),d0)
        qtmp(jb3,im) = qtmp(jb3,im)-d1
        qtmp(jb3,i) = qtmp(jb3,i)+d1
        d0 = max(0._8,qtmp(jb3,i+1))
        d2 = min(-qtmp(jb3,i),d0)
        qtmp(jb3,i+1) = qtmp(jb3,i+1)-d2
        qtmp(jb3,i) = qtmp(jb3,i)+d2+tiny
      endif
    end do
    i = im
    qtmp_tad(j,i-1) = qtmp_tad(j,i-1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i-1)))
    d0_tad = 0.d0
  endif
end do
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  do j = j1, j2
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2 = min(-qtmp(j,i),d0)
      qtmp(j,i+1) = qtmp(j,i+1)-d2
      qtmp(j,i) = qtmp(j,i)+d2+tiny
    endif
  end do
end do
i = 1
do j = j1, j2
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  if (qtmp(j,i) .lt. 0.) then
    d0 = max(0._8,qtmp(j,im))
    d1 = min(-qtmp(j,i),d0)
    qtmp(j,im) = qtmp(j,im)-d1
    qtmp(j,i) = qtmp(j,i)+d1
    d0 = max(0._8,qtmp(j,i+1))
    d2_tad = d2_tad+qtmp_tad(j,i)
    d2_tad = d2_tad-qtmp_tad(j,i+1)
    d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d2_tad = 0.d0
    qtmp_tad(j,i+1) = qtmp_tad(j,i+1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i+1)))
    d0_tad = 0.d0
    d1_tad = d1_tad+qtmp_tad(j,i)
    d1_tad = d1_tad-qtmp_tad(j,im)
    do i = 1, im
      do jb5 = j1, j2
        qtmp(jb5,i) = q(i,jb5)
      end do
    end do
    do i = 2, im-1
      do jb5 = j1, j2
        if (qtmp(jb5,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb5,i-1))
          d1 = min(-qtmp(jb5,i),d0)
          qtmp(jb5,i-1) = qtmp(jb5,i-1)-d1
          qtmp(jb5,i) = qtmp(jb5,i)+d1
          d0 = max(0._8,qtmp(jb5,i+1))
          d2 = min(-qtmp(jb5,i),d0)
          qtmp(jb5,i+1) = qtmp(jb5,i+1)-d2
          qtmp(jb5,i) = qtmp(jb5,i)+d2+tiny
        endif
      end do
    end do
    i = 1
    d0 = max(0._8,qtmp(j,im))
    d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
    qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
    d1_tad = 0.d0
    do i = 1, im
      do jb6 = j1, j2
        qtmp(jb6,i) = q(i,jb6)
      end do
    end do
    do i = 2, im-1
      do jb6 = j1, j2
        if (qtmp(jb6,i) .lt. 0.) then
          d0 = max(0._8,qtmp(jb6,i-1))
          d1 = min(-qtmp(jb6,i),d0)
          qtmp(jb6,i-1) = qtmp(jb6,i-1)-d1
          qtmp(jb6,i) = qtmp(jb6,i)+d1
          d0 = max(0._8,qtmp(jb6,i+1))
          d2 = min(-qtmp(jb6,i),d0)
          qtmp(jb6,i+1) = qtmp(jb6,i+1)-d2
          qtmp(jb6,i) = qtmp(jb6,i)+d2+tiny
        endif
      end do
    end do
    qtmp_tad(j,im) = qtmp_tad(j,im)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,im)))
    d0_tad = 0.d0
  endif
end do
q(:,:) = qh(:,:)
do i = 1, im
  do j = j1, j2
    qtmp(j,i) = q(i,j)
  end do
end do
do i = 2, im-1
  d0_tad = 0.d0
  d1_tad = 0.d0
  d2_tad = 0.d0
  do j = j1, j2
    d0_tad = 0.d0
    d1_tad = 0.d0
    d2_tad = 0.d0
    if (qtmp(j,i) .lt. 0.) then
      d0 = max(0._8,qtmp(j,i-1))
      d1 = min(-qtmp(j,i),d0)
      qtmp(j,i-1) = qtmp(j,i-1)-d1
      qtmp(j,i) = qtmp(j,i)+d1
      d0 = max(0._8,qtmp(j,i+1))
      d2_tad = d2_tad+qtmp_tad(j,i)
      d2_tad = d2_tad-qtmp_tad(j,i+1)
      d0_tad = d0_tad+d2_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
      qtmp_tad(j,i) = qtmp_tad(j,i)-d2_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
      d2_tad = 0.d0
      qtmp_tad(j,i+1) = qtmp_tad(j,i+1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i+1)))
      d0_tad = 0.d0
      d1_tad = d1_tad+qtmp_tad(j,i)
      d1_tad = d1_tad-qtmp_tad(j,i-1)
      do ib1 = 1, im
        do jb7 = j1, j2
          qtmp(jb7,ib1) = q(ib1,jb7)
        end do
      end do
      d0 = max(0._8,qtmp(j,i-1))
      d0_tad = d0_tad+d1_tad*(0.5-sign(0.5d0,d0-(-qtmp(j,i))))
      qtmp_tad(j,i) = qtmp_tad(j,i)-d1_tad*(0.5+sign(0.5d0,d0-(-qtmp(j,i))))
      d1_tad = 0.d0
      do ib2 = 1, im
        do jb8 = j1, j2
          qtmp(jb8,ib2) = q(ib2,jb8)
        end do
      end do
      qtmp_tad(j,i-1) = qtmp_tad(j,i-1)+d0_tad*(0.5-sign(0.5d0,0._8-qtmp(j,i-1)))
      d0_tad = 0.d0
    endif
  end do
end do
do i = 1, im
  do j = j1, j2
    q_tae(i,j) = q_tae(i,j)+qtmp_tad(j,i)
    qtmp_tad(j,i) = 0.d0
  end do
end do

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine filew_tad


subroutine fillxy_tad( q, q_tae, im, jm, jfirst, jlast, acap, cosp )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: tiny = 1.e-20

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
integer :: jm
real(kind=r8) :: cosp(jm)
integer :: im
integer :: jfirst
integer :: jlast
real(kind=r8) :: q(im,jfirst:jlast)
real(kind=r8) :: q_tae(im,jfirst:jlast)

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
call filew_tad( q,q_tae,im,jm,jfirst,jlast,acap,tiny,cosp(2) )

end subroutine fillxy_tad


subroutine pfix_tad( q_tae, qp_tad, im, acap, cosp2 )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
real(kind=r8) :: acap
real(kind=r8) :: cosp2
integer :: im
real(kind=r8) :: q_tae(im)
real(kind=r8) :: qp_tad(im)

!==============================================
! declare local variables
!==============================================
integer :: i
real(kind=r8) :: pmean_tad
real(kind=r8) :: summ_tad
real(kind=r8) :: sump_tad

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
pmean_tad = 0.d0
summ_tad = 0.d0
sump_tad = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
do i = 1, im
  pmean_tad = pmean_tad+qp_tad(i)
  qp_tad(i) = 0.d0
  pmean_tad = pmean_tad+q_tae(i)
  q_tae(i) = 0.d0
end do
summ_tad = summ_tad+pmean_tad*(cosp2/(acap+cosp2*im))
sump_tad = sump_tad+pmean_tad*(acap/(acap+cosp2*im))
pmean_tad = 0.d0
sump_tad = sump_tad/dble(im)
do i = 1, im
  qp_tad(i) = qp_tad(i)+sump_tad
  q_tae(i) = q_tae(i)+summ_tad
end do

end subroutine pfix_tad


end module     fill_module_tad


#endif /* SPMD */
