#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine age_of_air_tl( im, km, jfirst, jlast, ng, time, pe, pe_tm, q, q_tm )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: a = 5.e-6/60.
real(kind=r8), parameter :: p_source = 75000.
real(kind=r8), parameter :: tiny = 1.e-6

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
integer :: km
integer :: ng
real(kind=r8) :: pe(im,km+1,jfirst:jlast)
real(kind=r8) :: pe_tm(im,km+1,jfirst:jlast)
real(kind=r8) :: q(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: q_tm(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: time

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: k
real(kind=r8) :: pm
real(kind=r8) :: pm_tl

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
#ifdef USE_OPENMP
!$omp parallel do private(i,j,k,pm,pm_tl)
#endif /* ! USE_OPENMP */
do k = 1, km
  do j = jfirst, jlast
    do i = 1, im
      pm_tl = 0.5*pe_tm(i,k+1,j)+0.5*pe_tm(i,k,j)
      pm = 0.5*(pe(i,k,j)+pe(i,k+1,j))
      if (time .lt. tiny) then
        q_tm(i,j,k) = 0.d0
        q(i,j,k) = 0.
      else if (pm .ge. p_source) then
        q_tm(i,j,k) = 0.d0
        q(i,j,k) = a*time
      endif
    end do
  end do
end do

end subroutine age_of_air_tl


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
subroutine age_of_air_tl( im, km, jfirst, jlast, ng, time, pe, pe_tm, q, q_tm )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare parameters
!==============================================
real(kind=r8), parameter :: a = 5.e-6/60.
real(kind=r8), parameter :: p_source = 75000.
real(kind=r8), parameter :: tiny = 1.e-6

!==============================================
! declare arguments
!==============================================
integer :: im
integer :: jfirst
integer :: jlast
integer :: km
integer :: ng
real(kind=r8) :: pe(im,km+1,jfirst:jlast)
real(kind=r8) :: pe_tm(im,km+1,jfirst:jlast)
real(kind=r8) :: q(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: q_tm(im,jfirst-ng:jlast+ng,km)
real(kind=r8) :: time

!==============================================
! declare local variables
!==============================================
integer :: i
integer :: j
integer :: k
real(kind=r8) :: pm
real(kind=r8) :: pm_tl

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
#ifdef USE_OPENMP
!$omp parallel do private(i,j,k,pm,pm_tl)
#endif /* ! USE_OPENMP */
do k = 1, km
  do j = jfirst, jlast
    do i = 1, im
      pm_tl = 0.5*pe_tm(i,k+1,j)+0.5*pe_tm(i,k,j)
      pm = 0.5*(pe(i,k,j)+pe(i,k+1,j))
      if (time .lt. tiny) then
        q_tm(i,j,k) = 0.d0
        q(i,j,k) = 0.
      else if (pm .ge. p_source) then
        q_tm(i,j,k) = 0.d0
        q(i,j,k) = a*time
      endif
    end do
  end do
end do

end subroutine age_of_air_tl


#endif /* SPMD */
