#ifdef    SPMD
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     dependent_tl
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

contains
subroutine model2dependent_tl( m, y, yprog )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision
!use prognostics
use stepon, only : imr,jnp,nl,jfirst,jlast,kfirst,klast
use stepon, only : ng_d,ng_s

use control, only : ibeg_u,iend_u
use control, only : ibeg_v,iend_v
use control, only : ibeg_delp,iend_delp
use control, only : ibeg_pt,iend_pt
use control, only : ibeg_q,iend_q
use control, only : ibeg_tr,iend_tr

use mod_comm, only : mp_gather4d

use prognostics, only : dyn_prog
use prognostics, only : nc

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
integer :: m, m_nc
real(kind=r8) :: y(m)
type(dyn_prog) :: yprog

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
call mp_gather4d( yprog%u,y(ibeg_u),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,ng_d,ng_s,0 )
call mp_gather4d( yprog%v,y(ibeg_v),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,ng_s,ng_d,0 )
call mp_gather4d( yprog%pt,y(ibeg_pt),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,ng_d,ng_d,0 )
call mp_gather4d( yprog%q(:,:,:,1),y(ibeg_q),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,ng_d,ng_d,0 )

call mp_gather4d( yprog%delp,y(ibeg_delp),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,0,0,0 )

if (nc .gt. 1) then
    do m_nc = 2, nc
       call mp_gather4d( yprog%q(:,:,:,m_nc),y(ibeg_tr(m_nc-1)),imr,jnp,nl,1,jfirst,jlast,kfirst,klast,ng_d,ng_d,0 )
    enddo
endif

end subroutine model2dependent_tl


end module     dependent_tl


#else  /* SPMD */
!                           DISCLAIMER
!
!   This file was generated by TAF version 1.6.1
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     dependent_tl
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use dependent

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

contains
subroutine model2dependent_tl( m, y, y_tl )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.6.1   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use precision
use prognostics
use prognostics_tl
use control, only : ibeg_u,iend_u
use control, only : ibeg_v,iend_v
use control, only : ibeg_delp,iend_delp
use control, only : ibeg_pt,iend_pt
use control, only : ibeg_q,iend_q

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
integer :: m
real(kind=r8) :: y(m)
real(kind=r8) :: y_tl(m)

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
y_tl(ibeg_delp:iend_delp) = reshape(delp_tl(:,jfirst:jlast,:),(/1+iend_delp-ibeg_delp/))
y(ibeg_delp:iend_delp) = reshape(delp(:,jfirst:jlast,:),(/1+iend_delp-ibeg_delp/))
y_tl(ibeg_q:iend_q) = reshape(q_tl(:,jfirst:jlast,:,1),(/1+iend_q-ibeg_q/))
y(ibeg_q:iend_q) = reshape(q(:,jfirst:jlast,:,1),(/1+iend_q-ibeg_q/))
y_tl(ibeg_pt:iend_pt) = reshape(pt_tl(:,jfirst:jlast,:),(/1+iend_pt-ibeg_pt/))
y(ibeg_pt:iend_pt) = reshape(pt(:,jfirst:jlast,:),(/1+iend_pt-ibeg_pt/))
y_tl(ibeg_v:iend_v) = reshape(v_tl(:,jfirst:jlast,:),(/1+iend_v-ibeg_v/))
y(ibeg_v:iend_v) = reshape(v(:,jfirst:jlast,:),(/1+iend_v-ibeg_v/))
y_tl(ibeg_u:iend_u) = reshape(u_tl(:,jfirst:jlast,:),(/1+iend_u-ibeg_u/))
y(ibeg_u:iend_u) = reshape(u(:,jfirst:jlast,:),(/1+iend_u-ibeg_u/))

end subroutine model2dependent_tl


end module     dependent_tl


#endif /* SPMD */
